In [1]:
import numpy as np

In [2]:
def mat_mult(r):
    n = len(r) - 1
    M = [x[:] for x in n * [n * [0]]]

    for k in range(1, n):
        for i in range(n - k):
            val = float('inf')
            for j in range(i, i + k):
                new_val = M[i][j] + M[j + 1][i + k] + r[i] * r[j + 1] * r[i + k + 1]
                if new_val < val:
                    val = new_val
            M[i][i + k] = val

    return M

In [3]:
def print_example(r):
        m = mat_mult(r)
        print(f"Multiply matrices with dimensions:\nr:\n{r}")
        
        print(f"M:\n{np.array(m)}")
        print(f"Minimal number of multiplications: {m[0][-1]}")

In [6]:
print_example([10, 1, 10, 2])

Multiply matrices with dimensions:
r:
[10, 1, 10, 2]
M:
[[  0 100  40]
 [  0   0  20]
 [  0   0   0]]
Minimal number of multiplications: 40


In [5]:
print_example([30, 1, 40, 10, 25])

Multiply matrices with dimensions:
r:
[30, 1, 40, 10, 25]
M:
[[    0  1200   700  1400]
 [    0     0   400   650]
 [    0     0     0 10000]
 [    0     0     0     0]]
Minimal number of multiplications: 1400
