In [20]:
import numpy as np

## Labyrinth Search: RECURSIVE

In [21]:
W = np.matrix([[1,1,1,1,1,1,1,1,1,1],          ### transpose to convert to column order
               [1,0,1,1,0,1,0,1,0,1],          ### --> may use W[x,y] instead of W[y,x]
               [1,0,1,0,0,1,0,1,0,1],
               [1,0,0,0,1,1,0,1,0,1],
               [1,0,1,0,0,0,0,0,0,1],
               [1,0,1,0,1,1,1,1,0,1],
               [1,0,1,0,1,0,0,0,0,1],
               [1,0,1,0,1,0,1,1,1,1],
               [1,0,1,0,1,0,0,0,0,1],
               [1,1,1,1,1,1,1,1,1,1]]).transpose()

dir = ["N","O","S","W"]

walk = {"N": ( 0,-1),
        "O": ( 1, 0),
        "S": ( 0, 1),
        "W": (-1, 0)}

start = (1,1)
end   = (8,8) 
path  = []

##################################################

def SEARCH(P,Q):
    global path

    if P == Q:
        path = []
        return True
    else:
        for r in dir:
            x = P[0] + walk[r][0]
            y = P[1] + walk[r][1]

            if W[x,y] == 0:
                W[P] = 2
                if SEARCH((x,y),Q):
                    path = [r] + path
                    return True
                else:
                    W[P] = 3
        return False

##################################################

if SEARCH(start,end):
    W[end] = 2
    print(W.transpose())
    print()
    print(path)

[[1 1 1 1 1 1 1 1 1 1]
 [1 2 1 1 0 1 0 1 0 1]
 [1 2 1 3 3 1 3 1 3 1]
 [1 2 2 2 1 1 3 1 3 1]
 [1 0 1 2 2 2 2 2 2 1]
 [1 0 1 0 1 1 1 1 2 1]
 [1 0 1 0 1 2 2 2 2 1]
 [1 0 1 0 1 2 1 1 1 1]
 [1 0 1 0 1 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]]

['S', 'S', 'O', 'O', 'S', 'O', 'O', 'O', 'O', 'O', 'S', 'S', 'W', 'W', 'W', 'S', 'S', 'O', 'O', 'O']


## stack implementation based on single linked list

In [22]:
class Node:
    def __init__(self, item):
        self.item = item
        self.next = None
        
class Stack:
    def __init__(self):
        self.head = None
    
    def isEmpty(self):
        return self.head == None
    
    def push(self,item):
        new = Node(item)
        new.next = self.head
        self.head = new
        
    def pop(self):
        self.head = self.head.next
    
    def top(self):
        return self.head.item

## unit test: stack

In [23]:
S = Stack()

S.push(7)
S.push(5)
S.push(3)
S.push(1)

print(S.top(),S.isEmpty())
S.pop()
print(S.top(),S.isEmpty())
S.pop()
print(S.top(),S.isEmpty())
S.pop()
print(S.top(),S.isEmpty())
S.pop()
print(S.isEmpty())

1 False
3 False
5 False
7 False
True


## Labyrinth Search: ITERATIVE

In [24]:
W = np.matrix([[1,1,1,1,1,1,1,1,1,1],          ### transpose to convert to column order
               [1,0,1,1,0,1,0,1,0,1],          ### --> may use W[x,y] instead of W[y,x]
               [1,0,1,0,0,1,0,1,0,1],
               [1,0,0,0,1,1,0,1,0,1],
               [1,0,1,0,0,0,0,0,0,1],
               [1,0,1,0,1,1,1,1,0,1],
               [1,0,1,0,1,0,0,0,0,1],
               [1,0,1,0,1,0,1,1,1,1],
               [1,0,1,0,1,0,0,0,0,1],
               [1,1,1,1,1,1,1,1,1,1]]).transpose()

dir = ["N","O","S","W"]

walk = {"N": ( 0,-1),
        "O": ( 1, 0),
        "S": ( 0, 1),
        "W": (-1, 0)}

start = (1,1)
end   = (8,8) 
path  = []

##################################################

P = start
Q = end

S = Stack()

while (P != Q):
    for r in dir:
        x = P[0] + walk[r][0]
        y = P[1] + walk[r][1]

        if W[x,y] == 0:
            W[P] = 2
            S.push((P,r))
            P = (x,y)
            break
    else:
        W[P] = 3
        (P,r) = S.top()
        S.pop()
        W[P] = 0

W[end] = 2

while not S.isEmpty():
    path = [S.top()[1]] + path
    S.pop()

print(W.transpose())
print()
print(path)

[[1 1 1 1 1 1 1 1 1 1]
 [1 2 1 1 3 1 3 1 3 1]
 [1 2 1 3 3 1 3 1 3 1]
 [1 2 2 2 1 1 3 1 3 1]
 [1 0 1 2 2 2 2 2 2 1]
 [1 0 1 0 1 1 1 1 2 1]
 [1 0 1 0 1 2 2 2 2 1]
 [1 0 1 0 1 2 1 1 1 1]
 [1 0 1 0 1 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]]

['S', 'S', 'O', 'O', 'S', 'O', 'O', 'O', 'O', 'O', 'S', 'S', 'W', 'W', 'W', 'S', 'S', 'O', 'O', 'O']
